### ISSUE TITLE
Bug in Iterating the properties in application.conf.j2 template

### ISSUE THREAD

**Issue by risg07** [nerdynick/kafka-lag-exporter-ansible#2]
Ref: The application.conf.j2 file in the templates folder, line number: 29 & 38. 
In the iteration of the consumer_properties and admin_properties , the conflicting line is `{% for key,value in properties.consumer_properties.items() %} `which throws an error as properties is not defined.  
         

                {% if cluster.consumer_properties is defined %}
                {% for key,value in properties.consumer_properties.items() %}
                {{ key }}="{{ value }}"
                {% endfor %}
                {% endif %}
            }
            admin-client-properties = {
                {% include "kafka_client.conf.j2" %}
                
                {% if cluster.admin_properties is defined %}
                {% for key,value in properties.admin_properties.items() %}
                {{ key }}="{{ value }}"
                {% endfor %}
                {% endif %}
            }
It throws an error as 'properties is undefined'.

`[ FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'properties' is undefined"}]`

It works fine when i replace 'properties' with 'cluster'.

                {% if cluster.consumer_properties is defined %}
                {% for key,value in cluster.consumer_properties.items() %}
                {{ key }}="{{ value }}"
                {% endfor %}
                {% endif %}
            }
            admin-client-properties = {
                {% include "kafka_client.conf.j2" %}
                
                {% if cluster.admin_properties is defined %}
                {% for key,value in cluster.admin_properties.items() %}
                {{ key }}="{{ value }}"
                {% endfor %}
                {% endif %}
            }

**Comment by nerdynick** [comment]
This should be fixed now with V0.1.7.
